package com.finsight.assistant;

import jakarta.validation.Valid;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.util.List;

/**
 * REST controller for the Typology Intelligence Assistant.
 *
 * <p>Single endpoint: {@code POST /api/v1/assistant/query}
 *
 * <p>Returns 503 when Ollama is not running or the vector store is not initialised,
 * with a clear human-readable message explaining what to run.
 */
@RestController
@RequestMapping("/api/v1/assistant")
public class AssistantController {

    private static final Logger log = LoggerFactory.getLogger(AssistantController.class);

    private final AssistantService assistantService;

    public AssistantController(AssistantService assistantService) {
        this.assistantService = assistantService;
    }

    /**
     * Query the typology intelligence assistant.
     *
     * <p>Example request:
     * <pre>
     * POST /api/v1/assistant/query
     * Content-Type: application/json
     *
     * { "question": "What typologies involve coordinated trading across multiple accounts?" }
     * </pre>
     *
     * <p>Example response:
     * <pre>
     * {
     *   "answer": "Coordinated trading rings...",
     *   "suggestedRule": "Flag clusters of ≥3 traders... [UNREVIEWED — REQUIRES ANALYST SIGN-OFF]",
     *   "retrievedSources": ["04_fatf_collusion_rings.md"],
     *   "disclaimer": "This response is generated by a small on-prem RAG assistant..."
     * }
     * </pre>
     */
    @PostMapping("/query")
    public ResponseEntity<AssistantResponse> query(@Valid @RequestBody AssistantRequest request) {
        if (!assistantService.isReady()) {
            log.warn("Assistant query received but service is not ready (Ollama unavailable)");
            return ResponseEntity
                    .status(HttpStatus.SERVICE_UNAVAILABLE)
                    .body(new AssistantResponse(
                        "The Typology Intelligence Assistant is not available. " +
                        "Ensure Ollama is running and the required models are pulled:\n" +
                        "  ollama serve\n" +
                        "  ollama pull nomic-embed-text\n" +
                        "  ollama pull llama3.1:8b",
                        null,
                        List.of(),
                        "Service unavailable."
                    ));
        }

        log.info("Assistant query: {}", request.question());
        AssistantResponse response = assistantService.query(request.question());
        return ResponseEntity.ok(response);
    }
}
