package com.finsight.assistant;

import jakarta.annotation.PostConstruct;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.UUID;
import java.util.stream.Collectors;

/**
 * Typology Intelligence Assistant — on-prem RAG pipeline over curated regulatory documents.
 *
 * <h3>Pipeline</h3>
 * <ol>
 *   <li>Startup: load typology documents → embed each chunk via Ollama → store in InMemoryVectorStore.
 *   <li>Query: embed question → cosine-similarity search → top-K chunks → augmented prompt → Ollama generate.
 *   <li>Response: parse LLM output for "SUGGESTED RULE:" marker → return structured AssistantResponse.
 * </ol>
 *
 * <h3>Governance Constraints (enforced at the code level, not just in documentation)</h3>
 * <ul>
 *   <li>This service has <strong>NO JPA repository dependencies</strong> — it cannot read or
 *       write the trades table, surveillance_alerts table, or any other persistent store.
 *       This is verified by {@code AssistantGovernanceTest} using reflection.
 *   <li>Every response includes a mandatory disclaimer labelling all suggestions as unreviewed.
 *   <li>The word "SUGGESTED RULE" is parsed from LLM output and explicitly labelled
 *       "[UNREVIEWED — REQUIRES ANALYST SIGN-OFF]" in the response JSON.
 * </ul>
 *
 * <h3>What this is NOT</h3>
 * <ul>
 *   <li>Not fine-tuned on FinSight data.
 *   <li>Not evaluated with RAGAS or any LLM evaluation harness.
 *   <li>Not connected to the live rule engine — suggestions are text proposals only.
 *   <li>Not a multi-agent or agentic system.
 * </ul>
 */
@Service
public class AssistantService {

    private static final Logger log = LoggerFactory.getLogger(AssistantService.class);

    private static final String DISCLAIMER =
        "This response is generated by a small on-prem RAG assistant over curated regulatory " +
        "typology summaries. It is NOT legal advice, NOT a definitive compliance determination, " +
        "and any suggested rules are UNREVIEWED PROPOSALS that require analyst sign-off before " +
        "any action is taken. This assistant has NO write access to any trading system, rule " +
        "engine, or database.";

    // ── Dependencies — NO JpaRepository, NO TradeRepository, NO SurveillanceAlertRepository ──
    // The governance test (AssistantGovernanceTest) verifies this at test time via reflection.
    private final OllamaClient       ollamaClient;
    private final TypologyLoader     typologyLoader;
    private final InMemoryVectorStore vectorStore;

    @Value("${finsight.assistant.top-k-results:3}")
    private int topK;

    /** Set to true once typology documents are embedded and the store is populated. */
    private volatile boolean ready = false;

    public AssistantService(OllamaClient ollamaClient,
                             TypologyLoader typologyLoader,
                             InMemoryVectorStore vectorStore) {
        this.ollamaClient   = ollamaClient;
        this.typologyLoader = typologyLoader;
        this.vectorStore    = vectorStore;
    }

    /**
     * Index typology documents at startup. If Ollama is unavailable, logs a warning
     * and marks the service as not ready — the controller will return 503.
     */
    @PostConstruct
    public void initialize() {
        log.info("Initialising Typology Intelligence Assistant...");
        try {
            List<String[]> chunks = typologyLoader.loadDocumentChunks();
            for (String[] chunk : chunks) {
                String filename = chunk[0];
                String content  = chunk[1];
                float[] embedding = ollamaClient.embed(content);
                if (embedding.length > 0) {
                    vectorStore.addChunk(new DocumentChunk(
                            UUID.randomUUID().toString(), filename, content, embedding));
                }
            }
            ready = true;
            log.info("Typology Intelligence Assistant ready: {} document chunks indexed", vectorStore.size());
        } catch (OllamaClient.OllamaUnavailableException e) {
            log.warn("Typology Intelligence Assistant not ready: {}. " +
                     "Start Ollama with: ollama serve && ollama pull nomic-embed-text && ollama pull llama3.1:8b",
                     e.getMessage());
            ready = false;
        } catch (Exception e) {
            log.warn("Typology Intelligence Assistant failed to initialise: {}", e.getMessage(), e);
            ready = false;
        }
    }

    /** @return true if the vector store is populated and Ollama is reachable */
    public boolean isReady() { return ready; }

    /**
     * Execute the RAG pipeline for the given question.
     *
     * @param question natural language question from the compliance analyst
     * @return structured response with answer, optional suggested rule, sources, and disclaimer
     */
    public AssistantResponse query(String question) {
        // 1. Embed the query
        float[] queryEmbedding = ollamaClient.embed(question);

        // 2. Retrieve top-K relevant document chunks by cosine similarity
        List<DocumentChunk> retrieved = vectorStore.search(queryEmbedding, topK);

        if (retrieved.isEmpty()) {
            return new AssistantResponse(
                "No relevant typology documents were found for this query.",
                null,
                List.of(),
                DISCLAIMER
            );
        }

        // 3. Build augmented prompt
        String context = retrieved.stream()
                .map(c -> "--- Source: " + c.getSource() + " ---\n" + c.getContent())
                .collect(Collectors.joining("\n\n"));
        String prompt = buildPrompt(question, context);

        // 4. Generate response via Ollama LLM
        String rawResponse = ollamaClient.generate(prompt);

        // 5. Parse out any suggested rule — labelled as unreviewed
        String suggestedRule = extractSuggestedRule(rawResponse);

        // Remove the "SUGGESTED RULE:" line from the main answer to avoid duplication
        String answer = rawResponse
                .replaceAll("(?im)^\\s*SUGGESTED RULE:.*$", "")
                .trim();

        List<String> sources = retrieved.stream()
                .map(DocumentChunk::getSource)
                .distinct()
                .collect(Collectors.toList());

        log.info("Assistant query answered. Sources: {}. Suggested rule present: {}",
                sources, suggestedRule != null);

        return new AssistantResponse(answer, suggestedRule, sources, DISCLAIMER);
    }

    // ── Private helpers ───────────────────────────────────────────────────────

    private String buildPrompt(String question, String context) {
        return """
                You are a compliance analyst assistant at a trade surveillance firm.
                Your role is to review regulatory typology documents and suggest potential
                new surveillance rules or features for human analyst review.

                GOVERNANCE RULES — you MUST follow these exactly:
                1. Base your answer ONLY on the provided regulatory context below.
                2. If the context does not contain relevant information, say "The provided context
                   does not address this question directly."
                3. If you identify a pattern that could map to a new surveillance check, include
                   it on a dedicated line starting with exactly: SUGGESTED RULE: [your suggestion]
                4. Any suggestion is a proposal only — never claim it should be auto-applied.
                5. Do NOT invent regulatory citations not present in the context.

                Regulatory context:
                %s

                Analyst question: %s

                Provide a plain-language answer followed by a SUGGESTED RULE line if applicable.
                """.formatted(context, question);
    }

    /**
     * Extract the "SUGGESTED RULE:" line from the LLM response and append the
     * mandatory governance label.
     */
    private String extractSuggestedRule(String rawResponse) {
        if (rawResponse == null || rawResponse.isBlank()) return null;
        for (String line : rawResponse.split("\n")) {
            String trimmed = line.trim();
            if (trimmed.toLowerCase().startsWith("suggested rule:")) {
                String rule = trimmed.substring("suggested rule:".length()).trim();
                return rule + " [UNREVIEWED — REQUIRES ANALYST SIGN-OFF BEFORE ANY ACTION]";
            }
        }
        return null;
    }
}
